version: "3.8"
services: 
  next-demo:
    container_name: next-demo
    build: .
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
      - PORT=4001
    ports:
      - 4001:4001
